Dashboard draft
eclipsesource/cdtcloud-deploymentserver pull request #36
Opened 2022-01-14 19:34 UTC by theZasa

## Changes Proposed:
- First Draft of Dashboard
- To be discussed:
- Renaming of "Devices" -> "Connected Boards" 
- and "Types" -> "Board Types"

## Issues Addressed:
- None yet

## Tests Performed:
- Builds in Frontend

## How to Test the Changes:
- /packages/deployment-server-ui  yarn run dev 

## Known Issues and TODO List:
- [ ] replace mock data with real data
- [ ] fix padding of UI Elements
- [ ] make UI elements as responsive as possible
- [ ] do CSS

## How to Test PRs
1) First fetch the Pull-Request from the main repo, replacing `xx` with the ID of the PR:\
`git fetch git@github.com:eclipsesource/cdtcloud-deploymentserver.git pull/xx/head:pr_xx`
2) Checkout the Pull-Request, again replacing `xx` with the PR-ID:\
`git checkout pr_xx`
3) Perform the necessary tests for the PR

2022-01-16 19:02 UTC, theZasa commented
I suggest merging the current draft-state of the dashboard to use it as a baseline for further PRs. 
@WoH @Gozzim @KevinK-9

2022-01-18 19:23 UTC, WoH requested changes
Primarily blocking until the ico rights are clarified. The other things can be addressed in the meantime

2022-01-18 19:23 UTC, WoH commented on packages/deployment-server-ui/src/pages/Dashboard.tsx
> +import "./DashboardCSS.css";
```suggestion
import "./Dashboard.css";
```

and rename the file

2022-01-19 14:49 UTC, theZasa commented on packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget/TypeSelect.tsx
> -import * as React from "react";
This happend when i merged main into this branch

2022-01-19 16:40 UTC, theZasa commented on packages/deployment-server-ui/src/components/Dashboard/DeploymentsOverTimeGraph.tsx
> +export default defineFunctionalComponent(function DeploymentsOverTimeGraph() {
Will be adressed in cleanup

2022-01-19 17:48 UTC, theZasa commented
> Primarily blocking until the ico rights are clarified. The other things can be addressed in the meantime

Ico rights have been clarified. It is fine as it is under EPL

2022-01-19 17:49 UTC, WoH approved these changes

2022-01-19 17:52 UTC, merged